#!/bin/bash -f
#SBATCH --partition=SP2
#SBATCH --ntasks=1              # numero de CPUs - neste exemplo, 1 CPU
#SBATCH --cpus-per-task=1	# Number OpenMP Threads per process
#SBATCH -J aloca-1-cpu
#SBATCH --time=10:00:00         # Se voce nao especificar, o default é 8 horas. O limite é 480 horas


source /temporario2/9877294/anaconda3/etc/profile.d/conda.sh
conda activate

base_dir="/temporario2/9877294/ncbi_dataset/data"
output_base="/temporario2/9877294/Resultados_AntiSMASH"

mkdir -p "$output_base"

# Loop por todos os arquivos genomic.gbff encontrados
find "$base_dir" -type f -name "genomic.gbff" | while read -r input_file; do
    genome_dir=$(dirname "$input_file")
    genome_name=$(basename "$genome_dir")
    output_dir="${output_base}/${genome_name}_antismash"

    echo ">> Processando: $input_file"
    echo ">> Resultado em: $output_dir"

    antismash --genefinding-tool prodigal "$input_file" --output-dir "$output_dir"
done

